---
- name: Install prerequisites
  apt:
    name: 
      - "git"
      - "python3"
      - "python3-dev"
      - "python3-pip"
      - "python3-virtualenv"
    state: present
    update_cache: yes
  become: yes

- name: Install Molecule
  pip:
    name: "molecule[docker]"
    state: present
