---
- name: Install prerequisites
  apt:
    name:
      - gzip
    state: present
    update_cache: true
  become: yes

- name: Download and install Golang
  unarchive:
    src: https://go.dev/dl/go1.18.4.linux-amd64.tar.gz
    dest: /usr/local/go/bin
    remote_src: yes

- name: Add Golang dir to system-wide $PATH.
  copy:
    dest: /etc/profile.d/custom-path.sh
    content: 'PATH=$PATH:/usr/local/go'