---
- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - python3
      - python3-pip
      - python3-virtualenv
    state: present
    update_cache: yes
  become: yes

- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  become: yes

- name: Add Docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present
  become: yes

- name: Update packages
  apt:
    update_cache: yes
  become: yes

- name: Install Docker via apt
  apt:
    name:
      - docker-ce 
      - docker-ce-cli
      - containerd.io
    install-recommends: no
    state: present
    update_cache: yes
  become: yes
   
- name: Install docker-compose and supporting libraries
  pip:
    name:
      - docker-compose
    state: present
  become: yes

